// Copyright (c) Immutable Pty Ltd 2018 - 2023
// SPDX-License-Identifier: Apache-2.0
//
// This Solidity code creates a minimalist transparent proxy with a function to fetch
// the address of the contract being proxied to using the interface described in
// IWalletProxy.sol .
//

//********************** NOTE **********************
// This code is generated by Cursor / LLM using the WalletProxy.yul as the source.
// To be used as a reference only, correctness is not guaranteed.
//********************** NOTE **********************

pragma solidity ^0.8.3;

import "./IWalletProxy.sol";

contract WalletProxy is IWalletProxy {
    // Function selector for "PROXY_getImplementation()" - matches the Yul version
    bytes4 private constant PROXY_GET_IMPLEMENTATION_SELECTOR = 0x90611127;
    
    // Storage slot for implementation address (stored at contract's own address)
    // This matches the Yul logic: sstore(address(), implAddress)
    mapping(address => address) private _implementations;
    
    constructor(address implementation) {
        // Store the implementation address at the storage slot which is 
        // equivalent to the deployed address of this contract.
        // This matches the Yul logic: sstore(address(), implAddress)
        _implementations[address(this)] = implementation;
    }
    
    /// @dev Retrieve current implementation contract used by proxy
    function PROXY_getImplementation() external view override returns (address implementation) {
        return _implementations[address(this)];
    }
    
    // Fallback function that handles all other calls
    fallback() external payable {
        // Load the function selector (the first four bytes of calldata)
        bytes4 selector = bytes4(msg.data);
        
        // If this is the PROXY_getImplementation call, handle it directly
        if (selector == PROXY_GET_IMPLEMENTATION_SELECTOR) {
            address impl = _implementations[address(this)];
            assembly {
                mstore(0, impl)
                return(0, 0x20)
            }
        }
        
        // For all other calls, delegate to the implementation
        address implementation = _implementations[address(this)];
        require(implementation != address(0), "WalletProxy: implementation not set");
        
        assembly {
            // Copy calldata to memory
            calldatacopy(0, 0, calldatasize())
            
            // Execute delegate call
            let success := delegatecall(gas(), implementation, 0, calldatasize(), 0, 0)
            
            // Copy return data to memory
            returndatacopy(0, 0, returndatasize())
            
            // Return or revert based on success
            if iszero(success) {
                revert(0, returndatasize())
            }
            return(0, returndatasize())
        }
    }
    
    // Receive function for handling plain ETH transfers
    receive() external payable {
        // Delegate to implementation for ETH handling
        address implementation = _implementations[address(this)];
        require(implementation != address(0), "WalletProxy: implementation not set");
        
        assembly {
            // Execute delegate call with empty calldata
            let success := delegatecall(gas(), implementation, 0, 0, 0, 0)
            
            // Copy return data to memory
            returndatacopy(0, 0, returndatasize())
            
            // Return or revert based on success
            if iszero(success) {
                revert(0, returndatasize())
            }
            return(0, returndatasize())
        }
    }
}
